#include "nsISupports.idl"

interface nsIDOMHTMLDocument;
interface nsITreeNode;
[scriptable, uuid(63fe2585-b14f-442e-8c06-939e87c9902b)]
interface ILayoutAnalysis :nsISupports
{
     void SetDocument(in nsIDOMHTMLDocument doc);
     void SetKMeanAlg(in AUTF8String alg);
     void GetResult(out nsITreeNode tree);
     void SetClassCount(in unsigned long n);
     void SetFilterPath(in DOMString path);
};
