#include "nsISupports.idl"

interface nsIUrlAtt;
interface nsIColAtt;
interface nsIDOMDocument;
interface nsIPersistentProperties;
[scriptable, uuid(1cefedee-8475-47ff-98e6-3404c8b636ec)]
interface nsIColFetcher:nsISupports
{
     attribute nsIColAtt col;
     void SetDocument(in nsIDOMDocument doc);
     void SetProperty(in nsIPersistentProperties prop);
     long GetUrlLength();
     void GetUrlItem(in long index,out nsIUrlAtt url);
};
