#include "nsISupports.idl"

interface nsIUrlAtt;

[scriptable, uuid(03416f9b-5460-4799-8e7f-6673e12246ce)]
interface nsIIndexDoc:nsISupports
{
	attribute AUTF8String Title;
	attribute AUTF8String PublishDate;
	attribute AUTF8String Source;
	attribute AUTF8String Author;
	attribute AUTF8String Content;
	attribute AUTF8String Fields;

	void SetUrl(in nsIUrlAtt url_attr);
	void GetUrl(out nsIUrlAtt url_attr);
	void AddField(in AUTF8String fieldname, in AUTF8String fieldvalue);
};
