#include "nsISupports.idl"

interface nsIUrlAtt;
[scriptable, uuid(99424107-692a-4df6-9577-5869311b12b0)]
interface nsIUrlIO:nsISupports
{
     const unsigned short LOCAL_FILE   = 1;
     const unsigned short DATABASE     = 2;
     const unsigned short NETWORK      = 3;
     void GetURL(out nsIUrlAtt url,in unsigned short stat);
     void GetURLByLayer(out nsIUrlAtt url,in unsigned short stat,in unsigned short stlay,in unsigned short endlay);
     void GetURLByCol(out nsIUrlAtt url,in unsigned short stat,in unsigned long colId);
     void SetLocation(in AUTF8String location);
     void GetType(out unsigned short type);
     void UpdateStat(in nsIUrlAtt url,in unsigned short stat);
     void UpdateALL(in nsIUrlAtt url,in unsigned short stat);
     void UpdateCol(in nsIUrlAtt url,in AUTF8String colName,in AUTF8String value,in unsigned short stat);
     void PutURL(in nsIUrlAtt url);
     void GetURLID(in AUTF8String url,out unsigned long id);
     void GetURLbyID(out nsIUrlAtt url,in long id);
     void UpdatebyID(in long id,in AUTF8String colName,in AUTF8String value,in unsigned short stat);
     void UpdateStatByHash(in AUTF8String hash,in unsigned short stat);
};
