#include "nsISupports.idl"


[scriptable, uuid(2e5632c1-e046-4a50-9b47-496dbb9d3cb4)]
interface nsIUrlAtt:nsISupports
{
     attribute long Id;
     attribute AUTF8String Hash;
     attribute AUTF8String Link;
     attribute AUTF8String Title;
     attribute unsigned short Layer;
     attribute AUTF8String urlType;
     attribute AUTF8String conType;
     attribute AUTF8String conAtt;
     attribute long colId;
     attribute long nextId;
     attribute long parId;
     void SetURL(in AUTF8String Title,in AUTF8String Link,in unsigned long colId);
};
