#include "nsISupports.idl"

interface nsIPersistentProperties;
interface nsIDOMDocument;
interface nsIIDXCreator;
interface nsIUrlAtt;

[scriptable, uuid(1a0cbfc4-f991-4bfd-90ec-f97b882c716c)]
interface nsIDOMAnalysis:nsISupports
{
	PRUint32 Analysis(in nsIDOMDocument doc);
	void SetCurUrl(in nsIUrlAtt url_attr);
	void SetProperty(in nsIPersistentProperties p);
	void SaveWrapper();
	void LoadConfig();
	void SetIdxCreator(in nsIIDXCreator creator);

	void GetClusterAttr(in PRUint32 cid, out PRUint32 attr);
	void SetClusterType(in PRUint32 cid, in PRUint32 type);
};
