#include "nsISupports.idl"

interface nsIUrlAtt;
interface nsCStringArray;

[scriptable, uuid(65c713d8-8967-45ef-afcd-493ea13bea37)]
interface nsIClusterDBHandle:nsISupports
{
	void SetLocation(in AUTF8String location);	
	void SaveWrapRules(in PRInt32 con_type, in PRInt32 con_attr, in AUTF8String rules);
	void LoadWrapRules(in PRInt32 con_type, out AUTF8String rules);
	void SetPageType(in nsIUrlAtt url, in PRInt32 type);
	void InsertNewPage(in nsIUrlAtt url);
	void GetURLID(in AUTF8String url, out PRUint32 id);

	void UpdateClusterType(in PRInt32 con_type, in PRInt32 con_attr);
	
	void SavePage(in PRInt32 url_id, in AUTF8String type);
	void GetPage(out PRInt32 uid, out AUTF8String page);

	void SetConType(in PRInt32 url_id, in PRInt32 con_type);
	void GetNumberOfCluster(out PRInt32 num);
	void GetClusterID([array, size_is(count)]out PRUint32 ids, out PRUint32 count);
	void GetPageByConType(in PRUInt32 con_type, in PRUint32 num, in nsCStringArray docs, out PRUint32 count);

        void GetClusterType(in PRUInt32 name, out PRUint32 type);
};
