#include "nsISupports.idl"


[scriptable, uuid(5d9f8bd2-1dc8-4f09-b9d0-786cb1ad2473)]
interface nsIIDXCreator:nsISupports
{
     void SetReference(in AUTF8String refer);
     void SetTitle(in AUTF8String title);
     void SetDate(in AUTF8String date);
     void SetField(in AUTF8String name,in AUTF8String value);
     void SetDB(in AUTF8String db);
     void SetContent(in AUTF8String htmlContent);
     void GetIDX(out AUTF8String idx);
     void SendIDX(in AUTF8String url);
};
