#include "nsISupports.idl"

interface nsIChlAtt;
[scriptable, uuid(d046d058-af28-4f47-8c9b-7707b2d34b27)]
interface nsIChlIO:nsISupports
{
     const unsigned short LOCAL_FILE   = 1;
     const unsigned short DATABASE     = 2;
     const unsigned short NETWORK      = 3;
     void GetChl(out nsIChlAtt chl);
     void SetLocation(in AUTF8String location);
     void GetType(out unsigned short type);
     void PutChl(in nsIChlAtt chl);
     void GetChlByID(out nsIChlAtt chl,in long id);
     void UpdateByID(in long id,in AUTF8String colName,in AUTF8String value);
};
