#include "nsISupports.idl"
interface nsIDOMNode;
interface nsISupportsArray;
[scriptable, uuid(f4882709-fc1f-4dab-bd56-91987b91eced)]
interface nsITreeNode :nsISupports
{
     attribute long mX;
     attribute long mY;
     attribute long mW;
     attribute long mH;
     attribute long index;
     attribute nsIDOMNode node;
     void AddSubTree(in nsITreeNode tree);
     void PrintTree();
     void GetSubTree(out nsISupportsArray array);
     long GetArea();
     void SetTreeBox(in long x,in long y,in long w,in long h);
     void ClearSub();
     double GetWHRate();
     void SetClass([array, size_is(cv_size)]in long cv,in unsigned long cv_size);
     void CutTree([array, size_is(id_size)]in long id,in unsigned long id_size);
     void CutTreeForChl([array, size_is(id_size)]in long id,in unsigned long id_size);
     long GetClassId();
     boolean IsBigBox();
     void GetTreeText(out AUTF8String text);
};