#include "nsISupports.idl"

interface nsIIndexDoc;

[scriptable, uuid(952610dc-5157-4dcb-bc13-7f8ec0429e00)]
interface nsIDocHandle:nsISupports
{
	void SaveIDX(in nsIIndexDoc idx);

	void SetLocation(in AUTF8String location);
};
